recipe: default.v1
language: en
pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: openai-gpt-4o
  prompt_template: prompt_templates/command_generator_prompt.jinja2
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
assistant_id: 20250123-car-assistant
